### ISSUE TITLE
Psp Tools

### ISSUE THREAD

**Issue by Ninjacoderhsi** [Ninjacoderhsi/Psp-Tools#2]
![Screenshot_۲۰۲۱۰۸۳۱-۱۶۰۵۲۶_Psp Tools.jpg](https://user-images.githubusercontent.com/89408667/131495655-bd540ccb-66e2-465f-ad2b-3041532606de.jpg)

Best Runer psp Games 3x Speed in Ppsspp App And ppsspp Gold
Code Editor ini Files 
![Screenshot_۲۰۲۱۰۸۳۱-۱۶۰۶۵۱_Psp Tools.jpg](https://user-images.githubusercontent.com/89408667/131495870-ba26ca4c-5a07-4b15-a611-78ba8c5517d5.jpg)
![Screenshot_۲۰۲۱۰۸۳۱-۱۶۰۶۴۸_Psp Tools.jpg](https://user-images.githubusercontent.com/89408667/131495882-7c450569-1d5d-4f4c-b6f5-c9434315b60a.jpg)

**Comment by hosni009** [comment]
Why this issue ?

**Comment by Ninjacoderhsi** [comment]
> Why this issue ?

Code editor Version later
